# -*- coding: utf-8 -*-

{
    'name': 'Safety Master',
    'version': '0.01',
    'category': 'Services',
    'author': "JADESi",
    'description': """Anwendung für die Arbeitsabläufe in der Arbeitssicherheit""",
    'depends': ['portal', 'mail','hr'],
    'summary': 'Anwendung für die Arbeitsabläufe in der Arbeitssicherheit',
    'website': 'https://www.jadesi.de',
    'data': [
        'security/ir.model.access.csv',
        'data/safety_master_mail_data.xml',
        'views/safety_master_assets.xml',
        'views/safety_master_equipment_category_views.xml',
        'views/safety_master_views.xml',
        'wizard/mail_activity_edit_wizard_views.xml',
        'views/safety_master_mail_activity_views.xml',
        'report/begehung_safety_master.xml',
        'report/hazard_qr_code.xml',
        'report/folgebegehung_safety_master.xml',
        'report/gefaerdungsbeurteilung_safety_master.xml',
        'report/protocol_betriebsanweisung_template.xml',
        'report/gefahrstoff_verzeichnis.xml',
        'report/unterweisung.xml',
        'report/safety_master_betriebsanweisung_gefahrstoffe.xml',
        'report/safety_master_betriebsanweisung_psa.xml',
        'views/safety_master_menu.xml',
        'views/safety_master_protocol_views.xml',
        'views/safety_master_repair_view.xml',
        'views/safety_master_customer_view.xml',
        'views/safety_master_equipment_portal_templates.xml',
        'views/safety_master_res_users_views.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False
}